# Generated by Django 5.0.4 on 2024-06-08 04:38

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('item_price', models.FloatField()),
                ('item_image', models.ImageField(upload_to='menu_images/')),
                ('item_category', models.CharField(max_length=50)),
                ('item_is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_no', models.CharField(max_length=21)),
                ('address', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_description', models.CharField(max_length=40)),
                ('restaurant_address', models.CharField(max_length=50)),
                ('restaurant_phone', models.CharField(max_length=40)),
                ('restaurant_image', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant_rating', models.FloatField()),
                ('restaurant_delivery_charge', models.FloatField()),
                ('restaurant_cusine', models.CharField(max_length=25)),
                ('restaurant_is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('delivery_address', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='app1.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.restaurant'),
        ),
    ]
