# Generated by Django 5.0.4 on 2024-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_product_cart_items_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=35)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('landmark', models.CharField(max_length=25)),
                ('pincode', models.IntegerField(max_length=6)),
                ('default_address', models.BooleanField(default=False)),
            ],
        ),
    ]
