# Generated by Django 5.0.4 on 2024-12-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
